ARG OMERO_WEB_IMAGE=cellularimagingcf/omeroweb:latest
FROM ${OMERO_WEB_IMAGE}

USER root

COPY dist/wheelhouse/ /tmp/omero-plugin-wheelhouse/
COPY docker/90-omero-analysis-chat.omero /opt/omero/web/config/90-omero-analysis-chat.omero

RUN /opt/omero/web/venv3/bin/python -m pip install \
        --no-index --find-links /tmp/omero-plugin-wheelhouse \
        /tmp/omero-plugin-wheelhouse/omero_analysis_chat-*.whl \
    && rm -rf /tmp/omero-plugin-wheelhouse \
    && chmod 0644 /opt/omero/web/config/90-omero-analysis-chat.omero

USER omero-web
