from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r"^$", views.analysis, name="omero_analysis_index"),
    re_path(
        r"^runtime-sandbox/$",
        views.runtime_sandbox,
        name="omero_analysis_runtime_sandbox",
    ),
    re_path(
        r"^runtime/(?P<asset_path>[-\w./]+)$",
        views.runtime_asset,
        name="omero_analysis_runtime_asset",
    ),
    re_path(
        r"^api/session/keepalive/$",
        views.session_keepalive,
        name="omero_analysis_session_keepalive",
    ),
    re_path(
        r"^panel/(?P<object_type>\w+)/(?P<object_id>\d+)/$",
        views.panel,
        name="omero_analysis_panel",
    ),
    re_path(
        r"^api/launch-context/(?P<object_type>\w+)/(?P<object_id>\d+)/$",
        views.launch_context,
        name="omero_analysis_launch_context",
    ),
    re_path(r"^api/context-token/$", views.context_token, name="omero_analysis_token"),
    re_path(
        r"^api/context/(?P<object_type>\w+)/(?P<object_id>\d+)/$",
        views.context,
        name="omero_analysis_context",
    ),
    re_path(
        r"^api/attachments/(?P<object_type>\w+)/(?P<object_id>\d+)/$",
        views.attachments,
        name="omero_analysis_attachments",
    ),
    re_path(
        r"^api/hierarchy/(?P<object_type>\w+)/(?P<object_id>\d+)/$",
        views.hierarchy,
        name="omero_analysis_hierarchy",
    ),
    re_path(
        r"^api/attachment/(?P<annotation_id>\d+)/download/$",
        views.download_attachment,
        name="omero_analysis_download",
    ),
    re_path(
        r"^api/attachments/(?P<object_type>\w+)/(?P<object_id>\d+)/upload/$",
        views.upload_result,
        name="omero_analysis_upload",
    ),
    re_path(
        r"^api/workspaces/(?P<object_type>\w+)/(?P<object_id>\d+)/snapshots/$",
        views.workspace_snapshots,
        name="omero_analysis_workspace_snapshots",
    ),
    re_path(
        r"^api/workspace-snapshot/(?P<annotation_id>\d+)/download/$",
        views.download_workspace_snapshot,
        name="omero_analysis_workspace_snapshot_download",
    ),
    re_path(
        r"^api/pipelines/(?P<object_type>\w+)/(?P<object_id>\d+)/templates/$",
        views.pipeline_templates,
        name="omero_analysis_pipeline_templates",
    ),
    re_path(
        r"^api/pipeline-template/(?P<annotation_id>\d+)/download/$",
        views.download_pipeline_template,
        name="omero_analysis_pipeline_download",
    ),
    re_path(
        r"^api/notebook/(?P<annotation_id>\d+)/download/$",
        views.download_notebook,
        name="omero_analysis_notebook_download",
    ),
    re_path(
        r"^api/notebooks/(?P<object_type>\w+)/(?P<object_id>\d+)/upload/$",
        views.upload_notebook,
        name="omero_analysis_notebook_upload",
    ),
    re_path(
        r"^api/workspace-sync/(?P<object_type>\w+)/(?P<object_id>\d+)/"
        r"(?P<workspace_id>[-\w]+)/$",
        views.workspace_sync_status,
        name="omero_analysis_workspace_sync_status",
    ),
    re_path(
        r"^api/workspace-sync/(?P<object_type>\w+)/(?P<object_id>\d+)/"
        r"(?P<workspace_id>[-\w]+)/plan/$",
        views.workspace_sync_plan,
        name="omero_analysis_workspace_sync_plan",
    ),
    re_path(
        r"^api/workspace-sync/(?P<object_type>\w+)/(?P<object_id>\d+)/"
        r"(?P<workspace_id>[-\w]+)/apply/$",
        views.workspace_sync_apply,
        name="omero_analysis_workspace_sync_apply",
    ),
    re_path(
        r"^api/workspace-sync/(?P<object_type>\w+)/(?P<object_id>\d+)/"
        r"(?P<workspace_id>[-\w]+)/remove/$",
        views.workspace_sync_remove,
        name="omero_analysis_workspace_sync_remove",
    ),
    re_path(
        r"^api/workspace-library/(?P<object_type>\w+)/(?P<object_id>\d+)/$",
        views.workspace_library,
        name="omero_analysis_workspace_library",
    ),
    re_path(
        r"^api/workspace-dataset/(?P<dataset_id>\d+)/$",
        views.workspace_dataset,
        name="omero_analysis_workspace_dataset",
    ),
    re_path(
        r"^api/workspace-library/item/(?P<annotation_id>\d+)/download/$",
        views.workspace_library_download,
        name="omero_analysis_workspace_library_download",
    ),
    re_path(
        r"^api/settings/(?P<object_type>\w+)/(?P<object_id>\d+)/$",
        views.analysis_settings,
        name="omero_analysis_settings",
    ),
    re_path(
        r"^api/workflow-skills/$",
        views.workflow_skills,
        name="omero_analysis_workflow_skills",
    ),
    re_path(
        r"^api/integrations/zarr-viewer/$",
        views.zarr_viewer_integration,
        name="omero_analysis_zarr_viewer_integration",
    ),
    re_path(
        r"^api/workflow-skills/(?P<workflow_key>[a-zA-Z0-9_-]+)/"
        r"(?P<skill_name>[a-z0-9-]+)/$",
        views.workflow_skill_package,
        name="omero_analysis_workflow_skill",
    ),
    re_path(
        r"^api/workflow-skills/refresh/$",
        views.refresh_workflow_skills,
        name="omero_analysis_refresh_workflow_skills",
    ),
]
